site_name: "Lempire Curriculum"
theme:
  name: material

nav:
  - Home: index.md
  - Foundations:
    - Intro: foundations/intro.md
# Include custom CSS
extra_css:
  - assets/css/style.css

# Include custom JavaScript
extra_javascript:
  - assets/js/script.js
plugins:
  - search