site_name: "Mein Curriculum"
site_url: "https://username.github.io/repo-name/"
use_directory_urls: true

theme:
  name: material

# Assets einbinden
extra_css:
  - assets/css/style.css

extra_javascript:
  - assets/js/script.js
